### PR TITLE
ftp: fix OPTS UTF8 ON for Filezilla Server

### LINKED ISSUE #77: filezilla-server: UTF8 mode is always enabled. No need to send this command.
Hi,

The ftpd "filezilla-server" does respond to `OPTS UTF8 ON` with `202 UTF8 mode is always enabled. No need to send this command.`

This package then throws error.

For compatibility with filezilla-server, this package should accept 202 as an okay response for `OPTS UTF8 ON` and return err=nil.

Thanks,
~mappu

### PR DESCRIPTION
**Pull request by mappu**
Closes #77

### CODE REVIEW

File: ftp.go [hunk 1]
```diff
@@ -186,6 +186,13 @@ func (c *ServerConn) setUTF8() error {
 		return err
 	}
 
+	// The ftpd "filezilla-server" has FEAT support for UTF8, but always returns
+	// "202 UTF8 mode is always enabled. No need to send this command." when
+	// trying to use it. That's OK
```
Comment (shurcooL) [inline ftp.go]: Nitpick, there's a period missing at the end of the last sentence there.
